### ISSUE TITLE
[Feature] User login

### ISSUE THREAD

**Issue by Jack-Papel** [ItsSammyM/mafia-rust#10]
### Feature

Make the login button functional, so that you can sign in and play under an account

### Task list

- [ ] Determine which auth provider to use
- [ ] Determine which database to use
- [ ] Store user account data
- [ ] Make login button functional

**Comment by jpdagostino** [comment]
## Problem Definition
Create an authentication system that can interact with both the game client and game server. It should also store information in a database.

## Design Statement
I will create a micro service written in rust. It will support username/password authentication, sending emails, passkeys, and follow best practices. It will use a relational database such as PostgreSQL to handle data.

## Constraints
- Rust Programming Language
- SQL Support
- Must securely store information

## Deliverables
Microservice

**Comment by Jack-Papel** [comment]
I think for the sake of our users, we should handle authorization using a third party like Auth0, so there is little to no possibility of a breach.

Knowing Sam's friends, they will use their master password for everything including this. One small hiccup and a lot of accounts are made vulnerable.

If this is something you're really passionate about, maybe we can consider it. But I would much rather go with the tried-and-true

**Comment by jpdagostino** [comment]
That's a good point. Auth0 is free up to 25000mau. I will look into that then.

**Comment by jpdagostino** [comment]
[branch: authentication-server](https://github.com/mafia-rust/mafia/tree/authentication-server)

I decided to use passkeys instead but will also implement a provider system so future authentication systems can be added.

**Comment by jpdagostino** [comment]
Using MongoDB because it will have to store data from multiple auth providers. Considered Cassandra, but the library isn't updated as frequently.
