### ISSUE TITLE
[Feature] Game logs

### ISSUE THREAD

**Issue by Jack-Papel** [ItsSammyM/mafia-rust#9]
### Feature

Keep logs of each game for later perusal or traversal

### Task list

- [ ] Determine which logs to store
- [ ] Determine a format for logs which is human readable and traversable
- [ ] Determine where to store logs (database?)
- [ ] Determine logging framework if any
- [ ] Store game logs
